### ISSUE TITLE
trouble importing unity package

### ISSUE THREAD

**Issue by BillCrowther** [nol1fe/delaunator-sharp-unitypackage#1]
Hi 
I get this error when I try to import the unity package via the git url. Cant get the json route to work either. Bit new to github so maybe something silly. thanks for any advice

Cannot perform upm operation: Unable to add package [https://github.com/nol1fe/delaunator-sharp-unitypackage]:
  Package name 'https://github.com/nol1fe/delaunator-sharp-unitypackage' is invalid. [InvalidParameter]
UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by BillCrowther** [comment]
Ok noob error here - reading error messages carefully says that I dont have Git installed on my system so that will be a problem...

> Hi
> I get this error when I try to import the unity package via the git url. Cant get the json route to work either. Bit new to github so maybe something silly. thanks for any advice
> 
> Cannot perform upm operation: Unable to add package [https://github.com/nol1fe/delaunator-sharp-unitypackage]:
> Package name 'https://github.com/nol1fe/delaunator-sharp-unitypackage' is invalid. [InvalidParameter]
> UnityEditor.EditorApplication:Internal_CallUpdateFunctions()

**Comment by nol1fe** [comment]
I'm glad you found out the solution! 
Cheers :)
