### ISSUE TITLE
Create a release for package management

### ISSUE THREAD

**Issue by runette** [nol1fe/delaunator-sharp-unitypackage#2]
I would like to create a link from your Unity Package to the [Open-UPM](https://openupm.com/) package registry - since that is our projects preferred way of managing dependencies.

I just need one thing from you to do that. Open UPM uses the tags of a project to identify what to build - but you do not have any tags. Can you just create a release with a valid SemVer as the tag - "v1.0.0" would do nicely - and everything else will happen automatically.

Thanks

**Comment by nol1fe** [comment]
Hello @runette 

I've added tag with current version of Delaunator - v1.0.5

https://github.com/nol1fe/delaunator-sharp/releases/tag/v1.0.5 - main project
https://github.com/nol1fe/delaunator-sharp-unitypackage/releases/tag/v.1.0.5

Cheers

**Comment by runette** [comment]
Thanks you for this ...

BUT - you created the tag as `v.1.0.5` which OpenUPM is not accepting as a valid semver. It will accept `1.0.5` or `v1.0.5` but not with a dot after the v.

Sorry to be a pain but if there is any way you could create another release with either 1.0.5 or v1.0.5 as the tag (GH won't complain since the tag is still unique) then OpenUPM will automatically pick that up and hopefully process it.

You can see the package page here.

https://openupm.com/packages/com.nol1fe.delaunator/?subPage=readme 

Thanks again and I should say thank you for this package. It is a truly awesome piece of work :)

**Comment by runette** [comment]
Thanks. All working now and you have even got two stars already :)
